export const products = [
  { name: 'Form Ceramic Vase', category: 'Objects', price: 68, compareAtPrice: 84, image: 'https://images.unsplash.com/photo-1578500494198-246f612d3b3d?auto=format&fit=crop&w=900&q=85', badge: 'BESTSELLER', color: 'Chalk', description: 'A sculptural silhouette in hand-finished stoneware. Made to hold a branch, or nothing at all.' },
  { name: 'Everyday Linen Throw', category: 'Textiles', price: 128, compareAtPrice: null, image: 'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=900&q=85', badge: '', color: 'Oat', description: 'Washed Belgian linen with a soft, lived-in feel from day one.' },
  { name: 'Arc Table Lamp', category: 'Lighting', price: 186, compareAtPrice: null, image: 'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=900&q=85', badge: 'NEW', color: 'Warm white', description: 'A quiet glow, wherever the evening takes you. Powder-coated steel and a linen shade.' },
  { name: 'Sunday Market Tote', category: 'Accessories', price: 42, compareAtPrice: null, image: 'https://images.unsplash.com/photo-1590874103328-eac38a683ce7?auto=format&fit=crop&w=900&q=85', badge: '', color: 'Natural', description: 'Room for the market, the beach, and everything in between. Organic cotton canvas.' },
  { name: 'Still Life Candle', category: 'Objects', price: 36, compareAtPrice: null, image: 'https://images.unsplash.com/photo-1603006905003-be475563bc59?auto=format&fit=crop&w=900&q=85', badge: '', color: 'Cedar & Fig', description: 'A slow-burning soy candle that fills the room with cedarwood, fig leaf, and a hint of smoke.' },
  { name: 'Cloud Cotton Cushion', category: 'Textiles', price: 74, compareAtPrice: null, image: 'https://images.unsplash.com/photo-1584100936595-c0654b55a2e2?auto=format&fit=crop&w=900&q=85', badge: 'LOW STOCK', color: 'Terracotta', description: 'Relaxed cotton-linen cover and a feather-soft insert. The perfect finishing touch.' },
  { name: 'Ripple Glass Set', category: 'Objects', price: 54, compareAtPrice: null, image: 'https://images.unsplash.com/photo-1513506003901-1e6a229e2d15?auto=format&fit=crop&w=900&q=85', badge: '', color: 'Clear', description: 'Four hand-blown glasses with a subtle ripple texture. A little everyday occasion.' },
  { name: 'Curve Oak Side Table', category: 'Furniture', price: 248, compareAtPrice: 310, image: 'https://images.unsplash.com/photo-1499933374294-4584851497cc?auto=format&fit=crop&w=900&q=85', badge: '−20%', color: 'Natural oak', description: 'Solid FSC-certified oak, softened edges, and a handy shelf. Built to last generations.' },
];
